apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld
  labels:
    run: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      run: helloworld
  template:
    metadata:
      labels:
        run: helloworld
    spec:
      containers:
      - name: helloworld
        image: hello_world
        imagePullPolicy: Never